[workspace]
members = [
  "crates/core",
  "crates/macro",
  "crates/dom",
  "crates/router",
  "crates/ssr",
  "crates/testing",
  "crates/cli",
  "tests",
  "examples/todo-app",
]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/VryptLabs/rustweb"
rust-version = "1.75"

[workspace.dependencies]
rustweb-core = { path = "crates/core", version = "1.0.0" }
rustweb-macro = { path = "crates/macro", version = "1.0.0" }
rustweb-dom = { path = "crates/dom", version = "1.0.0" }
rustweb-router = { path = "crates/router", version = "1.0.0" }
rustweb-ssr = { path = "crates/ssr", version = "1.0.0" }
rustweb-testing = { path = "crates/testing", version = "1.0.0" }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
